services:
  postgres:
    image: postgres:17-alpine
    container_name: booking-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bookingservice_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
